### PR TITLE
Rip FE legacy

### PR DESCRIPTION
**Pull request by Moldy64**
I was going on the Forever Engine for some issues answers but it turns out it is gone, went skid daddle.

### CODE REVIEW

**Comment by Zoxycamente** [comment]
what the fuck happened to get deleted?

**Comment by Zoxycamente** [comment]
actually apparently Yoshubs profile which was deleted from github

**Comment by Zoxycamente** [comment]
Yoshubs' twitter profile was also deleted

**Comment by Zoxycamente** [comment]
from what i understand
shubs
Was canceled
and deleted all your accounts
and she doing it
ended up deleting the forever engine page

**Comment by Moldy64** [comment]
dang idk what about tsu all of her mods are forever engine

**Comment by Zoxycamente** [comment]
From what I understand,  can still use this engine in mods

**Comment by Moldy64** [comment]
yes

**Pull request closed without merging**
